name: Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: ci
        run: yarn --cwd profit-system install --immutable --immutable-cache --check-cache

      - name: build
        run: yarn --cwd profit-system build
